services:
  - type: web
    name: promperu-sistematizacion
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SYSTEM_ADMIN_USERNAME
        value: jvillaverdemontes
      - key: DB_SSLMODE
        value: require
      - key: DB_PORT
        value: "5432"
      - key: DB_CONN_MAX_AGE
        value: "60"
