# Generated by Django 6.0.7 on 2026-08-02 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atencion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180, unique=True)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MapeoColumna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encabezado_origen",
                    models.CharField(
                        help_text="Encabezado normalizado detectado en Excel",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "campo_destino",
                    models.CharField(
                        help_text="empresa.nombre, empresa.region, rating.total o criterio:<codigo>",
                        max_length=300,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CriterioRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.SlugField(max_length=255, unique=True)),
                (
                    "tipo_dato",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("booleano", "Sí/No"),
                            ("numero", "Número"),
                            ("fecha", "Fecha"),
                        ],
                        default="texto",
                        max_length=20,
                    ),
                ),
                (
                    "puntaje_maximo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criterios",
                        to="rating.categoriarating",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmpresaRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condicion_sunat", models.CharField(blank=True, max_length=120)),
                ("linea", models.CharField(blank=True, max_length=180)),
                ("producto", models.TextField(blank=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("clasificacion", models.CharField(blank=True, max_length=80)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="atencion.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportacionRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo_nombre", models.CharField(max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("filas_detectadas", models.PositiveIntegerField(default=0)),
                ("filas_importadas", models.PositiveIntegerField(default=0)),
                ("filas_actualizadas", models.PositiveIntegerField(default=0)),
                ("filas_ignoradas", models.PositiveIntegerField(default=0)),
                ("filas_fallidas", models.PositiveIntegerField(default=0)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ValorCriterio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_texto", models.TextField(blank=True)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("valor_booleano", models.BooleanField(blank=True, null=True)),
                (
                    "puntaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valores",
                        to="rating.criteriorating",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios",
                        to="rating.empresarating",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="criteriorating",
            constraint=models.UniqueConstraint(
                fields=("categoria", "nombre"), name="criterio_categoria_nombre_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="valorcriterio",
            constraint=models.UniqueConstraint(
                fields=("rating", "criterio"), name="valor_rating_criterio_unico"
            ),
        ),
    ]
