# Generated by Django 6.0.7 on 2026-08-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criteriorating",
            options={"ordering": ["categoria__orden", "orden", "nombre"]},
        ),
        migrations.AddField(
            model_name="criteriorating",
            name="ayuda",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="criteriorating",
            name="es_puntaje",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="criteriorating",
            name="opciones",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="criteriorating",
            name="orden",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="criteriorating",
            name="origen_excel",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
