# Generated by Django 6.0.7 on 2026-08-07 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_alter_perfilasesor_rol'),
        ('rating', '0003_evaluacionvisita_perfilevaluacionempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evaluacionvisita',
            constraint=models.UniqueConstraint(fields=('atencion',), name='evaluacion_unica_por_atencion'),
        ),
    ]
