# Generated by Django 6.0.7 on 2026-08-14 02:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0004_atencion_detalle_consulta_atencion_hora'),
        ('rating', '0004_evaluacionvisita_evaluacion_unica_por_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionvisita',
            name='anio_evaluacion',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='evaluacionvisita',
            name='fecha_evaluacion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='evaluacionvisita',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='atencion.atencion'),
        ),
    ]
