# Generated by Django 6.0.7 on 2026-08-02 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atencion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionRealizada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Acción frecuente",
                "verbose_name_plural": "Acciones frecuentes",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("color", models.CharField(default="#64748b", max_length=7)),
                ("es_cerrado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Estado de atención",
                "verbose_name_plural": "Estados de atención",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GestionAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion_otro", models.CharField(blank=True, max_length=250)),
                ("observaciones", models.TextField(blank=True)),
                ("iniciada", models.DateTimeField(default=django.utils.timezone.now)),
                ("resuelta", models.DateTimeField(blank=True, null=True)),
                (
                    "accion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seguimiento.accionrealizada",
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atencion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestion",
                        to="atencion.atencion",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gestiones",
                        to="seguimiento.estadoatencion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeguimientoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detalle", models.TextField(verbose_name="SEGUIMIENTO")),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos",
                        to="seguimiento.gestionatencion",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
