# Generated by Django 6.0.7 on 2026-08-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionatencion',
            name='accion_realizada',
            field=models.TextField(blank=True, verbose_name='ACCIÓN REALIZADA'),
        ),
        migrations.AddField(
            model_name='gestionatencion',
            name='es_practicante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestionatencion',
            name='estado_atencion',
            field=models.CharField(choices=[('atendido', 'Atendido'), ('atendido_derivado', 'Atendido y derivado'), ('sin_atender', 'Sin atender')], default='sin_atender', max_length=24, verbose_name='ESTADO DE LA ATENCIÓN'),
        ),
        migrations.AddField(
            model_name='gestionatencion',
            name='estado_seguimiento',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='en_proceso', max_length=20, verbose_name='SEGUIMIENTO'),
        ),
    ]
