# Generated by Django 6.0.7 on 2026-08-02 03:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Región",
                "verbose_name_plural": "Regiones",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectores",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("RUC", "RUC"),
                            ("DNI", "DNI"),
                            ("Pasaporte", "Pasaporte"),
                            ("Carné de Extranjería", "Carné de Extranjería"),
                        ],
                        max_length=30,
                        verbose_name="TIPO DE DOCUMENTO*",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=30, verbose_name="N° DEL DOCUMENTO"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="NOMBRE DE LA EMPRESA / INSTITUCIÓN / PERSONA NATURAL*",
                    ),
                ),
                (
                    "tipo_personeria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Persona Natural", "Persona Natural"),
                            (
                                "Persona Natural con Negocio",
                                "Persona Natural con Negocio",
                            ),
                            ("Persona Jurídica", "Persona Jurídica"),
                            ("Cooperativa", "Cooperativa"),
                            ("Asociación", "Asociación"),
                        ],
                        max_length=40,
                        verbose_name="TIPO DE PERSONERÍA",
                    ),
                ),
                (
                    "nombres_apellidos",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="NOMBRES Y APELLIDOS"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=120, verbose_name="CARGO"),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            (
                                "Empresa con Potencial Exportador",
                                "Empresa con Potencial Exportador",
                            ),
                            ("Exportador", "Exportador"),
                            ("Importador", "Importador"),
                            (
                                "Representante de una Institución",
                                "Representante de una Institución",
                            ),
                            ("Investigador", "Investigador"),
                            ("Estudiante", "Estudiante"),
                        ],
                        max_length=60,
                        verbose_name="TIPO DE USUARIO*",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9+() -]+$",
                                "Ingrese solo números y signos telefónicos.",
                            )
                        ],
                        verbose_name="TELÉFONO / CELULAR*",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-MAIL*")),
                (
                    "oferta_producto_servicio",
                    models.TextField(
                        verbose_name="OFERTA O PRODUCTO O SERVICIO CON EL QUE CUENTA O DE INTERÉS*"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresas",
                        to="atencion.region",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresas",
                        to="atencion.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Responsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsable",
                "verbose_name_plural": "Responsables",
                "ordering": ["orden", "nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Atencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="FECHA*"
                    ),
                ),
                (
                    "tipo_atencion",
                    models.CharField(
                        choices=[
                            ("WhatsApp", "WhatsApp"),
                            ("Correo Electrónico", "Correo Electrónico"),
                            ("Presencial", "Presencial"),
                            ("Telefónica", "Telefónica"),
                            ("Reunión Virtual", "Reunión Virtual"),
                            ("Visita a empresa", "Visita a empresa"),
                        ],
                        max_length=30,
                        verbose_name="TIPO DE ATENCIÓN*",
                    ),
                ),
                (
                    "tema_consulta",
                    models.TextField(verbose_name="REGISTRE EL TEMA DE CONSULTA*"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atenciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atenciones",
                        to="atencion.empresa",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atenciones",
                        to="atencion.responsable",
                        verbose_name="RESPONSABLE CON QUIEN DESEA ENTREVISTARSE*",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-creado"],
            },
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                fields=("tipo_documento", "numero_documento"),
                name="empresa_documento_unico",
            ),
        ),
    ]
