# Generated by Django 6.0.7 on 2026-08-04 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atencion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="atencion",
            name="anulada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="atencion",
            name="origen",
            field=models.CharField(
                choices=[
                    ("publico", "Formulario público"),
                    ("asesor", "Registrado por asesor"),
                    ("importado", "Importado"),
                ],
                default="publico",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="activa",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="atencion",
            name="tema_consulta",
            field=models.TextField(
                blank=True, verbose_name="REGISTRE EL TEMA DE CONSULTA"
            ),
        ),
        migrations.CreateModel(
            name="ArchivoAtenciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                ("generado", models.DateTimeField(auto_now_add=True)),
                ("archivo", models.FileField(upload_to="archives/%Y/%m/")),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("total_atenciones", models.PositiveIntegerField(default=0)),
                ("descargado_en", models.DateTimeField(blank=True, null=True)),
                ("depurado", models.BooleanField(default=False)),
                ("depurado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generado"],
            },
        ),
        migrations.CreateModel(
            name="PerfilAsesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.CharField(blank=True, max_length=30)),
                ("cargo", models.CharField(blank=True, max_length=150)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("asesor", "Asesor"),
                            ("bi", "Administrador / BI"),
                            ("admin", "Administrador general"),
                        ],
                        default="asesor",
                        max_length=20,
                    ),
                ),
                ("acceso_bi", models.BooleanField(default=False)),
                ("puede_archivar", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                (
                    "responsable",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perfil",
                        to="atencion.responsable",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_asesor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("crear", "Creación"),
                            ("editar", "Edición"),
                            ("eliminar", "Eliminación"),
                            ("archivar", "Archivo"),
                            ("depurar", "Depuración"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entidad", models.CharField(max_length=100)),
                ("objeto_id", models.CharField(blank=True, max_length=64)),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                ("antes", models.JSONField(blank=True, default=dict)),
                ("despues", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_auditadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
