# Generated by Django 6.0.7 on 2026-08-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_atencion_anulada_atencion_origen_empresa_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilasesor',
            name='rol',
            field=models.CharField(choices=[('asesor', 'Asesor'), ('coordinador', 'Coordinador'), ('bi', 'Administrador / BI'), ('admin', 'Administrador general')], default='asesor', max_length=20),
        ),
    ]
