# Generated by Django 6.0.7 on 2026-08-14 02:17

import atencion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_alter_perfilasesor_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='detalle_consulta',
            field=models.TextField(blank=True, verbose_name='DETALLAR CONSULTA'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='hora',
            field=models.TimeField(default=atencion.models.hora_local_actual, verbose_name='HORA DE ATENCIÓN'),
        ),
    ]
