# Generated by Django 6.0.7 on 2026-08-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0005_rellenar_hora_historica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='oferta_producto_servicio',
            field=models.TextField(verbose_name='OFERTA, PRODUCTO O SERVICIO QUE OFRECE*'),
        ),
    ]
