# Generated by Django 6.0.7 on 2026-08-14 03:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0006_alter_empresa_oferta_producto_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaFormularioPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin_programado', models.DateTimeField()),
                ('fin_real', models.DateTimeField(blank=True, null=True)),
                ('activado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_formulario_activadas', to=settings.AUTH_USER_MODEL)),
                ('desactivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_formulario_desactivadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='RespaldoLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=120)),
                ('ruta_storage', models.CharField(max_length=500, unique=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('total_atenciones', models.PositiveIntegerField(default=0)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_limpieza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generado'],
            },
        ),
    ]
